### ISSUE TITLE
#include <string> missing in expensive.hpp

### ISSUE THREAD

**Issue by springmeyer** [mapbox/hpp-skel#58]
It is best practice to have headers "include what they use" (https://include-what-you-use.org/). Short of running the https://include-what-you-use.org/ tool over the codebase (to catch missing includes) we can also use this trick to test that each header compiles on its own:

```
clang++ include/hello_world/expensive.hpp -std=c++11 -o /tmp/compiled-header
```

In this case we get:

```
include/hello_world/expensive.hpp:7:20: error: implicit instantiation of undefined template 'std::__1::basic_string<char,
      std::__1::char_traits<char>, std::__1::allocator<char> >'
inline std::string expensive(std::size_t work_to_do)
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:193:33: note: template is
      declared here
    class _LIBCPP_TYPE_VIS_ONLY basic_string;
                                ^
include/hello_world/expensive.hpp:14:35: error: no member named 'to_string' in namespace 'std'
        container.emplace(i, std::to_string(i));
                             ~~~~~^
include/hello_world/expensive.hpp:20:26: error: no member named 'to_string' in namespace 'std'
        if (item != std::to_string(i))
                    ~~~~~^
include/hello_world/expensive.hpp:29:17: error: implicit instantiation of undefined template 'std::__1::basic_string<char,
      std::__1::char_traits<char>, std::__1::allocator<char> >'
    std::string result = "Expensive work is finished";
                ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:193:33: note: template is
      declared here
    class _LIBCPP_TYPE_VIS_ONLY basic_string;
                                ^
4 errors generated.
```

Since `std::string` is used in the code but we are not including `#include <string>`. The likely reason this missing include is not creating a compile error in our tests is that `exclaim.hpp` is included before `expensive.hpp` and `exclaim.hpp` includes `<iostream>` (https://github.com/mapbox/hpp-skel/blob/17fb7bf436b8cf474cbb9e86ce2aaace1148e0da/include/hello_world/exclaim.hpp#L1) which likely it, itself, including `<string>`. In fact, `<iostream>` is overkill here, we should be including `<string>` in both files.

**Comment by springmeyer** [comment]
closed by #59
